# -*- coding: utf-8 -*-
"""data_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXOUjFKLmPB2jXq5vKrlH3F8NwEMIWe2
"""

import pandas as pd
def load_csv(path):
    return pd.read_csv(path)